CPPFLAGS=-I/opt/local/include/opencv -I/usr/include/opencv
LDFLAGS=-L/opt/local/lib -lcxcore -lhighgui -lcv
all:	warai
run:	warai
	#./warai --cascade=haarcascade_frontalface_alt2.xml 0
	while : ; do ./warai ; done
clean:
	rm warai
